# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'PersonalAgentsInAzure'

workspace:
  clean: all

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: '/usr/bin/ansible-playbook main.yml -i hosts'