---

- block:
  - name: Install PHP and it's dependencies
    yum:
      name: ['php', 'php-fpm', 'php-nrk-Predis']
      state: present
  - name: Enable php-fpm service
    service:
      name: php-fpm
      enabled: yes
  - name: Start php-fpm service
    service:
      name: php-fpm
      state: started
  become: true
  become_method: sudo