---

- block:
  - name: Install EPEL repository
    yum:
      name: epel-release
      state: installed
  - name: Install Nginx
    yum:
      name: nginx
      state: present
  - name: Start nginx
    service:
      name: nginx
      state: started
  become: true
  become_method: sudo