---

- block:
  - name: Install Redis database server
    yum:
      name: redis
      state: present
  - name: Enable Redis service
    service:
      name: redis
      enabled: yes
  - name: Start Redis service
    service:
      name: redis
      state: started
  - name: Enable webserver to connect to localhost where redis lives
    command: /usr/sbin/setsebool -P httpd_can_network_connect on
  become: true
  become_method: sudo