---

- block:
  - name: Enable index.php on nginx default web server
    lineinfile:
      path: /etc/nginx/nginx.conf
      line: '            index  index.php index.html index.htm;'
      insertafter: '        location'
      firstmatch: yes
  - name: Enable php parsing on default web server
    blockinfile:
      path: /etc/nginx/nginx.conf
      block: |
                      location ~ \.php$ {
                            try_files $uri  = 404;
                            fastcgi_pass    127.0.0.1:9000;
                            fastcgi_index   index.php;
                            fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
                            fastcgi_param   SCRIPT_NAME $fastcgi_script_name;
                            include         fastcgi_params;
                      }
            
      insertbefore: '        error_page 404 /404.html;'
      backup: yes
  - name: Restart nginx
    service:
      name: nginx
      state: restarted
  become: true
  become_method: sudo